name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ README.md ]
  workflow_dispatch:
  
jobs:

  macos:
    name: Test on macOS
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Build and test
      run: ./scripts/test.sh

  # linux:
  #   name: Test on Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: swift-actions/setup-swift@v2
  #     with:
  #       swift-version: "6.0.2"
  #   - uses: actions/checkout@v3
  #   - name: Test
  #     run: ./scripts/test.sh
